name: reminder
description: A Flutter reminder app MVP with local notifications and hive storage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_timezone: ^5.0.1
  uuid: ^4.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#1A1A25"
    theme_color: "#7C3AED"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/en.json
    - assets/translations/tr.json
